import uid from "../Components/Functions/uid";

const animalTeams = {
  teams: [
    {
      name: "Tiger",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Lion",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Elephant",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Whale",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Antelop",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Zebra",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Leopard",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Cheetar",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Crocodile",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Hippopotamus",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Ant",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Bear",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Aligator",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Fox",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Hyena",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Racoon",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Cat",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Eagle",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Dog",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Jaguar",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
  ],

  relegatedTeams: [
    {
      name: "Cheetar",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Buffalo",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Dove",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Python",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Owl",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Chimpazee",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Monkey",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Gorilla",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Baboon",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Shark",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Dolphin",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
  ],
};

export default animalTeams;
