import uid from "../Components/Functions/uid";

const carsTeams = {
  teams: [
    {
      name: "Camry",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Corrolla",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Benz",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Ford",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Innoson",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Sunny",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Peugot",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Lamborgini",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Ferrari",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "RAV 4",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "CRV",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Bently",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Pathfinder",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Pilot",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Highlander",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Cheverolet",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Acura",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Sienna",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Lexus",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Oddessy",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
  ],

  relegatedTeams: [
    {
      name: "Mazda",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Rolls Rolyce",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Jeep",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Optima",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Solara",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Honda",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Hyundia",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "4Matic",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "G-Wagon",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Hilux",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Picanto",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
  ],
};

export default carsTeams;
