import uid from "../Components/Functions/uid";

const fruitsTeams = {
  teams: [
    {
      name: "Mango",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Orange",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Pineapple",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Apple",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Pawpaw",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Garden Egg",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Carrot",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Cumcumber",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "lemon",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Lime",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Strawberrys",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Grapes",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Banana",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Pear",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Watermelon",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Cherry",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Tomato",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Onions",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Coconut",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Avacado Pear",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
  ],

  relegatedTeams: [
    {
      name: "cashew",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "groundnut",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "guava",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Citrus",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Peanut",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Plantain",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
  ],
};

export default fruitsTeams;
