import uid from "../Components/Functions/uid";

const phonesTeams = {
  teams: [
    {
      name: "Iphone 12",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Samsung note 21",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Nokia",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Itel",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Tecno",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Infinix note 8i",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Infinix note 11",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "One-plus",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Redmi note 10",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Oppo",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Vivo",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Lenovo",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Gionee",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Huawei",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "HTC",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Sony Ericson",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "H-Mobile",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Iphone 13",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Samsung s21",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
    {
      name: "Redmi 9T",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 2,
      midfield: 4,
      id: uid(),
      defence: 2,
      overall: 8,
    },
  ],

  relegatedTeams: [
    {
      name: "Soda",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Wiko",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Motorolla",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Fero",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "Tecno Camon 17",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
    {
      name: "T.. Mobile",
      league: {
        matchPlayed: 0,
        wins: 0,
        draw: 0,
        lose: 0,
        pts: 0,
        GD: 0,
        GF: 0,
        GA: 0,

        currentGoal: 0,
      },
      attack: 1.5,
      midfield: 3,
      id: uid(),
      defence: 1.5,
      overall: 6,
    },
  ],
};

export default phonesTeams;
